/*
 * @Author: your name
 * @Date: 2019-12-28 15:21:01
 * @LastEditTime : 2019-12-29 19:21:16
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /github/js/action/types.js
 */
'use strict';

export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  LOAD_GITHUB_REPOS_SUCCESS: 'LOAD_GITHUB_REPOS_SUCCESS',
  LOAD_GITHUB_REPOS_FAIL: 'LOAD_GITHUB_REPOS_FAIL',
  LOAD_GITHUB_DETAIL_REPOS_SUCCESS: 'LOAD_GITHUB_DETAIL_REPOS_SUCCESS',
  LOAD_GITHUB_DETAIL_REPOS_FAIL: 'LOAD_GITHUB_DETAIL_REPOS_FAIL',
  LOAD_GITHUB_TRENDING_SUCCESS: 'LOAD_GITHUB_TRENDING_SUCCESS',
  LOAD_GITHUB_TRENDING_FAIL: 'LOAD_GITHUB_TRENDING_FAIL',
  LOAD_PROPULAR_SUCCESS: 'LOAD_PROPULAR_SUCCESS',
  LOAD_PROPULAR_FAIL: 'LOAD_PROPULAR_FAIL',
  LOAD_PROPULAR_MORE_SUCCESS: 'LOAD_PROPULAR_MORE_SUCCESS',
  LOAD_PROPULAR_MORE_FAIL: 'LOAD_PROPULAR_MORE_FAIL',
  PROPULAR_REFRESH: 'LOAD_PROPULAR_REFRESH',
};
